import { ReportCategory } from '../shared/types';

export const SUPPLIER_REPORTS_DATA: ReportCategory[] = [
  {
    category: "Sales Summary",
    reports: [
      {
        title: "Sales by Product",
        description: "Detailed report showing revenue generated by each product (only delivered products).",
        details: "Displays product ID, product name, brand, product category, quantity sold, gross sales, discount amount, net sales, tax amount, total sales, average selling price, cost of goods sold, gross profit, and gross margin %.",
        points: [
          "Product Name, Brand, Category, Quantity Sold",
          "Gross Sales, Discount, Net Sales",
          "Tax Amount, Total Sales, Avg Price",
          "COGS, Gross Profit, Margin %"
        ]
      }
    ]
  },
  {
    category: "Product Summary",
    reports: [
      {
        title: "All Products Report",
        description: "Complete record of all products with detailed information.",
        details: "Includes product name, category, price, sale price, stock quantity, status, and creation date.",
        points: [
          "Product Name, Category, Brand",
          "Price, Sale Price",
          "Stock Quantity, Status",
          "Created Date, Active Status"
        ]
      },
      {
        title: "Inventory / Stock Report",
        description: "Detailed analysis of product inventory and stock levels.",
        details: "Shows product name, current stock, low stock alerts, last updated date, and stock movement history.",
        points: [
          "Product Name, Category, Brand",
          "Current Stock, Low Stock Alert",
          "Stock Value, Reorder Level",
          "Last Updated Date"
        ]
      },
      {
        title: "Category-wise Product Report",
        description: "Aggregated view showing product counts and sales by category.",
        details: "Displays category name, total products, average price, total stock value, and sales performance metrics.",
        points: [
          "Category Name, Total Products",
          "Average Price, Total Stock Value",
          "Total Stock Quantity",
          "Sales Performance Metrics"
        ]
      }
    ]
  }
];
