import { ReportCategory } from '../shared/types';

export const SUPPLIER_REPORTS_DATA: ReportCategory[] = [
  {
    category: "Sales Summary",
    reports: [
      {
        title: "Sales by Product",
        description: "Detailed report showing revenue generated by each product (only delivered products).",
        details: "Displays product ID, product name, brand, product category, quantity sold, gross sales, discount amount, net sales, tax amount, total sales, average selling price, cost of goods sold, gross profit, and gross margin %."
      }
    ]
  },
  {
    category: "Product Summary",
    reports: [
      {
        title: "All Products Report",
        description: "Complete record of all products with detailed information.",
        details: "Includes product name, category, price, sale price, stock quantity, status, and creation date."
      },
      {
        title: "Inventory / Stock Report",
        description: "Detailed analysis of product inventory and stock levels.",
        details: "Shows product name, current stock, low stock alerts, last updated date, and stock movement history."
      },
      {
        title: "Category-wise Product Report",
        description: "Aggregated view showing product counts and sales by category.",
        details: "Displays category name, total products, average price, total stock value, and sales performance metrics."
      }
    ]
  }
];
