"use client";

import { useState, useMemo, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from "@repo/ui/card";
import { Button } from "@repo/ui/button";
import { Download, Eye, Search, FileText } from 'lucide-react';
import { Input } from '@repo/ui/input';
import { Skeleton } from "@repo/ui/skeleton";
import { Report } from '../shared/types';

// Import table components
import { ProductSummaryTable } from './tables/ProductSummaryTable';
import { InventoryStockTable } from './tables/InventoryStockTable';
import { CategoryWiseProductTable } from './tables/CategoryWiseProductTable';
import { SalesByProductTable } from './tables/SalesByProductTable';

// Import constants, hooks, and modal wrapper
import { SUPPLIER_REPORTS_DATA } from './constants';
import { useSupplierFilters } from './hooks/useSupplierFilters';
import { ReportModal } from './modals/ReportModal';
import { ReportDetailModal } from '../shared/ReportDetailModal';

export default function SupplierReports() {
  // Use the custom hook for managing all filter states
  const { filters, updateFilter } = useSupplierFilters();
  
  // Single modal state - tracks which report is currently open
  const [openReportTitle, setOpenReportTitle] = useState<string | null>(null);
  const [searchTerm, setSearchTerm] = useState('');
  const [isLoading, setIsLoading] = useState(true);

  // Detail modal state for report info
  const [selectedReport, setSelectedReport] = useState<Report | null>(null);
  const [showDetailModal, setShowDetailModal] = useState(false);

  // Refresh states for each report
  const [productSummaryRefresh, setProductSummaryRefresh] = useState(0);
  const [salesByProductRefresh, setSalesByProductRefresh] = useState(0);

  // Report registry - maps report titles to their configuration
  const reportRegistry = useMemo(() => ({
    "Sales by Product": {
      title: "Sales by Product Report",
      description: "Detailed report showing revenue generated by each product (only delivered products).",
      component: (
        <SalesByProductTable
          product={filters.salesByProduct.product}
          category={filters.salesByProduct.category}
          brand={filters.salesByProduct.brand}
          status={filters.salesByProduct.status}
          isActive={filters.salesByProduct.isActive}
          triggerRefresh={salesByProductRefresh}
          onFiltersChange={(newFilters: any) => updateFilter('salesByProduct', newFilters)}
        />
      )
    },
    "All Products Report": {
      title: "All Products Report",
      description: "Complete record of all products with detailed information.",
      component: (
        <ProductSummaryTable
          product={filters.productSummary.product}
          category={filters.productSummary.category}
          brand={filters.productSummary.brand}
          status={filters.productSummary.status}
          isActive={filters.productSummary.isActive}
          region={filters.productSummary.region}
          triggerRefresh={productSummaryRefresh}
          onFiltersChange={(newFilters: any) => updateFilter('productSummary', newFilters)}
        />
      )
    },
    "Inventory / Stock Report": {
      title: "Inventory / Stock Report",
      description: "Detailed analysis of product inventory and stock levels.",
      component: (
        <InventoryStockTable
          product={filters.productSummary.product}
          category={filters.productSummary.category}
          brand={filters.productSummary.brand}
          triggerRefresh={productSummaryRefresh}
          onFiltersChange={(newFilters: any) => updateFilter('productSummary', newFilters)}
        />
      )
    },
    "Category-wise Product Report": {
      title: "Category-wise Product Report",
      description: "Aggregated view showing product counts and sales by category.",
      component: (
        <CategoryWiseProductTable
          product={filters.productSummary.product}
          category={filters.productSummary.category}
          brand={filters.productSummary.brand}
          triggerRefresh={productSummaryRefresh}
          onFiltersChange={(newFilters: any) => updateFilter('productSummary', newFilters)}
        />
      )
    }
  }), [filters, productSummaryRefresh, salesByProductRefresh, updateFilter]);

  // Simulate loading for 1.5 seconds
  useEffect(() => {
    const timer = setTimeout(() => {
      setIsLoading(false);
    }, 1500);
    return () => clearTimeout(timer);
  }, []);

  const handleViewClick = (report: Report) => {
    setOpenReportTitle(report.title);
  };

  const handleInfoClick = (report: Report) => {
    setSelectedReport(report);
    setShowDetailModal(true);
  };

  const filteredReportsData = useMemo(() => {
    if (!searchTerm) return SUPPLIER_REPORTS_DATA;

    return SUPPLIER_REPORTS_DATA
      .map(category => ({
        ...category,
        reports: category.reports.filter(report =>
          report.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
          report.description.toLowerCase().includes(searchTerm.toLowerCase())
        ),
      }))
      .filter(category => category.reports.length > 0);
  }, [searchTerm]);

  if (isLoading) {
    return (
      <div className="p-4 sm:p-6 lg:p-8 space-y-6">
        <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
          <div>
            <Skeleton className="h-8 w-64" />
            <Skeleton className="h-4 w-96 mt-2" />
          </div>
          <div className="relative">
            <Skeleton className="h-10 w-80" />
          </div>
        </div>
        <div className="space-y-8">
          {[...Array(2)].map((_, categoryIndex) => (
            <div key={categoryIndex}>
              <Skeleton className="h-7 w-48 mb-4" />
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {[...Array(3)].map((_, reportIndex) => (
                  <Card key={reportIndex}>
                    <CardHeader>
                      <Skeleton className="h-6 w-40 mb-2" />
                      <Skeleton className="h-4 w-full" />
                    </CardHeader>
                    <CardContent>
                      <div className="flex gap-2 w-full">
                        <Skeleton className="h-9 flex-1" />
                        <Skeleton className="h-9 w-9" />
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>
    );
  }
  const activeReport = openReportTitle ? (reportRegistry as Record<string, any>)[openReportTitle] : null;

  return (
    <div className="p-4 sm:p-6 lg:p-8">
      <div className="flex flex-col md:flex-row md:items-center md:justify-between mb-8">
        <div>
          <h1 className="text-3xl font-bold font-headline mb-2">Supplier Reports</h1>
          <p className="text-lg text-muted-foreground">
            Generate and download detailed product and sales reports.
          </p>
        </div>
        <div className="relative mt-4 md:mt-0">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input
            type="search"
            placeholder="Search reports..."
            className="w-full md:w-80 pl-10"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
          />
        </div>
      </div>

      <div className="space-y-10">
        {filteredReportsData.length > 0 ?
          filteredReportsData.map((category) => (
            <div key={category.category}>
              <h2 className="text-xl font-semibold font-headline text-gray-800 mb-4">{category.category}</h2>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {category.reports.map((report, index) => (
                  <Card key={index} className="hover:shadow-lg transition-shadow">
                    <CardHeader>
                      <CardTitle className="text-lg">{report.title}</CardTitle>
                      <CardDescription className="text-sm">{report.description}</CardDescription>
                    </CardHeader>
                    <CardContent>
                      <div className="flex gap-2">
                        <Button
                          onClick={() => handleViewClick(report)}
                          className="flex-1"
                          size="sm"
                        >
                          <Eye className="h-4 w-4 mr-2" />
                          View Report
                        </Button>
                        <Button
                          onClick={() => handleInfoClick(report)}
                          variant="outline"
                          size="sm"
                        >
                          <FileText className="h-4 w-4" />
                        </Button>
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </div>
            </div>
          )) : (
            <div className="text-center py-16 text-muted-foreground">
              <p>No reports found matching your search.</p>
            </div>
          )}
      </div>

      {/* Unified Report Modal - Single modal for all reports */}
      {activeReport && (
        <ReportModal
          isOpen={true}
          onClose={() => setOpenReportTitle(null)}
          title={activeReport.title}
          description={activeReport.description}
        >
          {activeReport.component}
        </ReportModal>
      )}

      {/* Report Detail Modal */}
      <ReportDetailModal
        isOpen={showDetailModal}
        onClose={() => setShowDetailModal(false)}
        report={selectedReport}
      />
    </div>
  );
}
