import dotenv from 'dotenv';
dotenv.config();

export const ENVIRONMENT = process.env.NODE_ENV;
export const BASE_URL = process.env.BASE_URL;
export const NEXT_PUBLIC_WEB_URL = process.env.NEXT_PUBLIC_WEB_URL;
export const NEXT_PUBLIC_CRM_URL = process.env.NEXT_PUBLIC_CRM_URL;
export const NEXT_PUBLIC_ADMIN_URL = process.env.NEXT_PUBLIC_ADMIN_URL;
export const MONGODB_URI = process.env.MONGODB_URI;
export const JWT_SECRET_USER = process.env.JWT_SECRET_USER;
export const JWT_SECRET_ADMIN = process.env.JWT_SECRET_ADMIN;
export const JWT_SECRET_VENDOR = process.env.JWT_SECRET_VENDOR;
export const JWT_SECRET_DOCTOR = process.env.JWT_SECRET_DOCTOR;
export const JWT_SECRET_SUPPLIER = process.env.JWT_SECRET_SUPPLIER;
export const JWT_REFRESH_SECRET_VENDOR = process.env.JWT_REFRESH_SECRET_VENDOR;
export const JWT_REFRESH_SECRET_ADMIN = process.env.JWT_REFRESH_SECRET_ADMIN;
export const JWT_REFRESH_SECRET_USER = process.env.JWT_REFRESH_SECRET_USER;
export const JWT_REFRESH_SECRET_DOCTOR = process.env.JWT_REFRESH_SECRET_DOCTOR;
export const JWT_REFRESH_SECRET_SUPPLIER = process.env.JWT_REFRESH_SECRET_SUPPLIER;
export const JWT_ACCESS_TOKEN_EXPIRY = process.env.JWT_ACCESS_TOKEN_EXPIRY;
export const JWT_REFRESH_TOKEN_EXPIRY = process.env.JWT_REFRESH_TOKEN_EXPIRY;
export const NEXT_PUBLIC_MAPBOX_API_KEY = process.env.NEXT_PUBLIC_MAPBOX_API_KEY;